/** Constants of Project's store */

/** Products */
export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';

/** Companies */
export const GET_COMPANIES_REQUEST = 'GET_COMPANIES_REQUEST';
export const GET_COMPANIES_SUCCESS = 'GET_COMPANIES_SUCCESS';
export const GET_COMPANIES_FAILURE = 'GET_COMPANIES_FAILURE';

/** Carts */
export const SAVE_TO_CART_REQUEST = 'SAVE_TO_CART_REQUEST';
export const SAVE_TO_CART_SUCCESS = 'SAVE_TO_CART_SUCCESS';
export const SAVE_TO_CART_FAILURE = 'SAVE_TO_CART_FAILURE';

export const UPDATE_CART_REQUEST = 'UPDATE_CART_REQUEST';
export const UPDATE_CART_SUCCESS = 'UPDATE_CART_SUCCESS';
export const UPDATE_CART_FAILURE = 'UPDATE_CART_FAILURE';

export const GET_CARTS_REQUEST = 'GET_CARTS_REQUEST';
export const GET_CARTS_SUCCESS = 'GET_CARTS_SUCCESS';
export const GET_CARTS_FAILURE = 'GET_CARTS_FAILURE';

export const DELETE_FROM_CART_REQUEST = 'DELETE_FROM_CART_REQUEST';
export const DELETE_FROM_CART_SUCCESS = 'DELETE_FROM_CART_SUCCESS';
export const DELETE_FROM_CART_FAILURE = 'DELETE_FROM_CART_FAILURE';